### ISSUE TITLE
Dependency issue with prettier

### ISSUE THREAD

**Issue by fmueller** [taniarascia/webpack-boilerplate#41]
First of all, thank you for your efforts. Your blog post about webpack configuration helped me a lot.

When I clone the repo and do `npm i` as wrote in the Readme, I run into a dependency issue. I'm not that deep into the npm dependency setup. But it looks like the `prettier-webpack-plugin`, which is 2 years old, references an outdated `prettier` major version.

Is there sth I can do on my side to work around this? I already tried downgrading `prettier` to 1.x major version but then webpack complains on version issues.

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: prettier@2.2.1
npm ERR! node_modules/prettier
npm ERR!   dev prettier@"^2.1.2" from the root project
npm ERR!   peer prettier@">=1.13.0" from eslint-plugin-prettier@3.3.0
npm ERR!   node_modules/eslint-plugin-prettier
npm ERR!     dev eslint-plugin-prettier@"^3.1.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev prettier-webpack-plugin@"^1.2.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: prettier@1.19.1
npm ERR! node_modules/prettier
npm ERR!   peer prettier@"^1.0.0" from prettier-webpack-plugin@1.2.0
npm ERR!   node_modules/prettier-webpack-plugin
```

**Comment by tpkahlon** [comment]
Hello @fmueller:

For development mode, you may continue to use stable release of Node to build your application. Such warnings can be ignored. I recommend choosing a legacy Node version (v10) on production server to bypass warning conflicts that may persist due to outdated versioning of `prettier-webpack-plugin`. To achieve that, please make following change in your fork:

- Create a `.nvmrc` file
- Enter `10.23.0` in its content and save it
- Deploy code to production

If someone has a better suggestion to tackle this issue, please feel free to share here.

**Comment by fmueller** [comment]
Thank you, I was using latest version of npm and not latest 6.x version. This cause some wrong dependency fetching.

Works now. 👍
